services:

  # ------------------------
  # Base de données MongoDB
  # ------------------------
  mongo:
    image: mongo
    container_name: sondage_mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  # ------------------------
  # Backend Python
  # ------------------------
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: sondage-backend:latest
    container_name: sondage_backend
    restart: unless-stopped
    env_file: ./backend/.env
    environment:
      - MONGO_URI=mongodb://mongo:27017/sondagedb
    ports:
      - "5000:5000"
    depends_on:
      - mongo

  # ------------------------
  # Frontend Angular + Tailwind
  # ------------------------
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: sondage-frontend:latest
    container_name: sondage_frontend
    restart: unless-stopped
    ports:
      - "8080:80"
    depends_on:
      - backend

volumes:
  mongo-data:
